### PR TITLE
Passwordless URL support

### PR DESCRIPTION
**Pull request by mieciu**
I've added tests and my solution of #19

### CODE REVIEW

**Comment by mieciu** [comment]
Hi @codeinthehole , 

just a friendly ping to receive some feedback regarding this change

**Comment by codeinthehole** [comment]
@mieciu Sorry yes - will look at this week.

**Comment by codeinthehole** [comment]
A nice improvement - thank you

**Comment by codeinthehole** [comment]
Am just waiting on a resolution to #22 before cutting a new release.

**Pull request merged**
