### PR TITLE
Added support for username/password setting

### PR DESCRIPTION
**Pull request by mieciu**
Those lines of code could actually help with elegant build of **full** URL, like this:

```
ELASTICSEARCH_URL = URL.from_string("FOUNDELASTICSEARCH_URL"))\
                           .scheme('https')\
                           .username(myuser)\
                           .password(os.environ['password'])\
                           .port('9243')
```

### CODE REVIEW

**Comment by codeinthehole** [comment]
Thanks. Not sure why I didn't include that functionality in the first place.

**Comment by mieciu** [comment]
You're welcome. Cannot wait for next release then, cheers!

**Comment by codeinthehole** [comment]
v1.1 now on PyPi with this change: https://pypi.python.org/pypi/purl/1.1

**Comment by mieciu** [comment]
Thanks for the fast info and have a good luck with the project!

**Pull request merged**
